### ISSUE TITLE
Running the selbal example

### ISSUE THREAD

**Issue by llrs** [UVic-omics/selbal#1]
I have installed the package following the vignette `devtools::install_github("UVic-omics/selbal")` but I can't run the examples provided in `selbal` help page.

You need to use following line `data("Crohn", package = "selbal")` in order to access them.

**Comment by UVic-omics** [comment]
Hi @llrs!

Thank you for you comment! I have tried the examples with the latest versions of both **R (3.5.1)** and **RStudio (1.1.456)** ,and I did not have any problem. Just calling `Crohn` I can acces to the Crohn's disease dataset.
What error message do you obtain if you call it directly?

Thanks again.

**Comment by llrs** [comment]
Yes, one can access when calling directly the object.
The error I get is that R is not able to locate the data when using `data(Crohn)`, so it won't pass the check of `R CMD check`
