### ISSUE TITLE
Combining species and genus

### ISSUE THREAD

**Issue by L-Boonstra** [UVic-omics/selbal#11]
Hi,

I would like to try and make a model combining the species and genus information. The idea is to combine both count tables into one. The total count will be double for each sample, each relative abundance will go down by half but the ratios will stay the same.

Do you think this would be possible to model with Selbal?

**Comment by UVic-omics** [comment]
For sure you can do, but you will probably have difficulties to interpret the results.

Best regards,

**Comment by L-Boonstra** [comment]
Thank you for the reply
