### ISSUE TITLE
accuracy per prediction group & groups of numerator and demominator

### ISSUE THREAD

**Issue by L-Boonstra** [UVic-omics/selbal#13]
Hello, I have a question regarding the output given by the Selbal output.

I would like to know what percentage of each group got predicted correctly besides the total AUC the accuracy plot shows. Besides that, I would like to know which group gets selected as the numerator and the denominator. Does Selbal store this information in its output?

Thank you in advance for your help.

**Comment by UVic-omics** [comment]
Hi @L-Boonstra ,

First of all thank you for using `selbal`.

First of all, let me tell you that you can see more information about the output of the functions here (https://htmlpreview.github.io/?https://github.com/UVic-omics/selbal/blob/master/vignettes/vignette.html). There you can read that:

**1)** You can get the AUC values through `$cv.tab`
**2)** The plots show you which are the variables included in the numerator and the numerator of the balance. Nevertheless, if you change them, remember that the AUC will be the same and the only thing that changes is the sign of the balance.

**Comment by L-Boonstra** [comment]
Hello, thank you very much for your answer and the information, but it wasn’t an answer to the question I tried to ask, so to explain it a bit better this time:


With CV.BAL.dic$accuracy.nvar I can view the accuracies for the number of variables used in the balances but this is only one value per number and with cv.tab I can see the frequencies of the balances and the percentage of the features.

If I for example have 100 samples in total of which 50 are case samples and 50 are control samples and I’m trying to predict whether a samples is case or control, then I can with accuracy.nvar see that x percent of those 100 samples are predicted correctly when using a balances of y variables. I would besides that like the know the AUC per group I’m trying to predict so x percent of the 50 case and x percent of the 50 control. That way I can see if one group is getting predicted a lot better than the other or if the accuracies are similar. Does Selbal store the AUC’s per group (case vs control) in the output?


Then the var.barplot shows which features are included in the numerator and the denominator, but does the output of Selbal say anywhere if the numerator is the case group or the control group?

**Comment by UVic-omics** [comment]
Hello!

Ok, this time I understood better your questions:

- Regarding the first one, I am sorry but `selbal` only provides the AUC without taking into account the specifcs for each group.

- Regarding the second question, take a look to the figure containing the boxplots and the density curves. For example the FIG 2 at (https://msystems.asm.org/content/3/4/e00053-18/figures-only) . You will see that the density curves shows higher values for "no" (non-CD) group. That means that "the numerator presents higher values than the denominator" which I think answers your question. Nevertheless, remember that we are working with a unique value, which is the diference between the means of the log-transformed values of the variables in the numerator and in the denominator.

**Comment by L-Boonstra** [comment]
Thank you for answering
