### ISSUE TITLE
Unable to install selbal

### ISSUE THREAD

**Issue by AlejandroSaborio** [UVic-omics/selbal#3]
I am trying to install selbal using devtools::install_github(repo = "UVic-omics/selbal"); however I got this error:
Error in read.dcf(path) : 
  Found continuation line starting ' 	 doParallel, ...' at begin of record.
How do I solve it?
Thanks in advance

**Comment by Jtrachsel** [comment]
There seems to be a bug in devtools right now.  See https://github.com/r-lib/devtools/issues/1900 

It also seems to only be affecting windows users.  I successfully installed the package on a linux system but the same command failed on windows.

You can get around this bug my cloning the github repository, then using the command "devtools::install_local('PATH_TO_WHERE_YOU_CLONED')"
