### ISSUE TITLE
selbal with continous data

### ISSUE THREAD

**Issue by janfelix** [UVic-omics/selbal#4]
Hi,

thanks for selbal! But, I am trying to run it with a continuous response variable (pH) and it I get the following error message: Error in eval(family$initialize) : y values must be 0 <= y <= 1

I defined x as the community composition of environmental microorganisms and y as the pH and simply call selbal(x,y). All data is formatted as numeric, row names match...

Anything I am doing wrong?

Thanks,

Jan

**Comment by UVic-omics** [comment]
Hi @janfelix!

Although you say that your data is numeric, can you check it using `class(y)`? The error message you talk about is very common to find when the response variable is not numeric.

If everything seems correct, I recomend you to redefine it as `new.y <- as.mueric(y)` and then run again `selbal(x, new.y)`.

I hope it helps you!

**Comment by janfelix** [comment]
Thanks for you reply!

I have tried it all and then tried it with mock data, I still get the same error every time. I looked at the selbal function but so far can't figure out where it goes wrong, but I'll let you know if i figure out what it is. Strangely enough the selbal.cv function works no problem...

Jan

**Comment by StevenMamet** [comment]
I'm running into the same issues as Jan. It's like selbal is expecting dichotomous data and won't run with continuous. selbal was working great for me a few weeks ago, but now I keep running into the same error. Any insights would be greatly appreciated. 

I've included a little snippet of my code:

> y
 [1] 183.744074   6.874282  58.204622 186.847277  79.068763 170.833935 798.204100  78.102526  44.705057 275.544972 551.028909 448.659708  50.161977
[14]   6.712448  95.005635  65.848057 621.316188  44.364967 110.155236 144.962259  87.159495 144.847124 141.562915 437.263447 369.336270  44.115890
[27] 213.007786 197.198258 543.059278 430.994526 613.251457 509.088714 258.902168 546.694573 307.108184 240.377085 507.673162 120.685000  65.077322
[40] 181.167976 245.508997  66.211954 128.207043  60.438991  72.770008  16.973105 118.220628 201.380589 348.520404 253.407255 121.721648 252.480502
[53]  74.314833 569.981675  49.509106 509.024862 396.159218  10.873791

> class(y)
[1] "numeric"

> b <- selbal(x, y, zero.rep = "bayes", th.imp = 0, logt = F, draw = T)

Error in eval(family$initialize) : y values must be 0 <= y <= 1  

Thanks!

**Comment by UVic-omics** [comment]
@janfelix @StevenMamet Thanks for your comments. We are checking out the last changes in the code to solve the problem as soon as possible. We will tell you when it is ready.

Thanks,

**Comment by UVic-omics** [comment]
@janfelix @StevenMamet  we have updated Selbal functions in order to solve this problem. Please install again Selbal package and check everything is working right.

**Comment by StevenMamet** [comment]
@UVic-omics @janfelix I reinstalled selbal and it works now with continuous data. Thanks for the quick fix!

**Comment by janfelix** [comment]
Hi, selbal.cv is working great now! Thanks a lot for the quick fix!

I did run into one issue however. Following your publication, where in the selbal command do I define the number of taxa as determined by selbal.cv? I searched the documentation and the vignettes and could not find the answer to this. The selbal documentation does not refer to "C" or "K opt".

**Comment by UVic-omics** [comment]
Hi @janfelix !

Although selbal is now working, we are still making some proofs. 
Answering your questions, you can use the variable `maxV' to indicate the optimal number of variables you got with 'selbal.cv()'.
