### ISSUE TITLE
Selbal for dichotomous response

### ISSUE THREAD

**Issue by jliu2019** [UVic-omics/selbal#6]
Hello,

Thanks for the great algorithm Selbal! 

I am trying to use Selbal on my microbiome data with continuous and dichotomous metadata. Selbal works fine with the continuous response. However, when I use the dichotomous variable as the response with default parameters for the same data set, I got warning messages, and the $opt.nvar was "Inf", balance$cv.accuracy was all "NA". Here is the warning message:

1: In min(which((ACC.mean > (ACC.mean[m] - ACC.se[m])) ==  ... :
  no non-missing arguments to min; returning Inf
2: glm.fit: algorithm did not converge
3: glm.fit: fitted probabilities numerically 0 or 1 occurred

Could you provide some hints about what happened and how to fix this? 

Thanks in advance!
Jianan

**Comment by UVic-omics** [comment]
Hi Jianan,
thank you for your comments. We hope we fixed your issue. Please, try to update Sebal now and use it again.

**Comment by jliu2019** [comment]
Hi, thanks for your quick update! I tried again, this time it did not have the "Inf" variable number and identified two variables as the global balance, but there were still warnings like this:

1: glm.fit: algorithm did not converge
2: glm.fit: fitted probabilities numerically 0 or 1 occurred

I also noticed that if I changed the order of taxa listed as columns in my input file, the two identified variables were also changed to different taxa. 

Could you help figure this out? Thanks!

**Comment by UVic-omics** [comment]
Hi Jianan, 
I guess you have a dataset with much more variables than samples (n << p). In this setting it is likely that several models (selected variables) provides the same performance. In other words, the solution is not unique).

**Comment by jliu2019** [comment]
That might be the reason. Thanks for your reply!
